/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BodyPart = IDL.Record({
  'id' : IDL.Text,
  'nameEn' : IDL.Text,
  'nameHi' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'descriptionHi' : IDL.Text,
  'modelType' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBodyPart' : IDL.Func([IDL.Text], [IDL.Opt(BodyPart)], ['query']),
  'getBodyParts' : IDL.Func([], [IDL.Vec(BodyPart)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BodyPart = IDL.Record({
    'id' : IDL.Text,
    'nameEn' : IDL.Text,
    'nameHi' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'descriptionHi' : IDL.Text,
    'modelType' : IDL.Text,
  });
  
  return IDL.Service({
    'getBodyPart' : IDL.Func([IDL.Text], [IDL.Opt(BodyPart)], ['query']),
    'getBodyParts' : IDL.Func([], [IDL.Vec(BodyPart)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };